import { SocialPost } from "./apify";

export const mockGachaItems = [
  {
    id: "1",
    name: "すみっコぐらし ぬいぐるみマスコット",
    nameEn: "Sumikko Gurashi Plush Mascot",
    description: "人気キャラクターすみっコぐらしのぬいぐるみガチャ。全6種類。",
    imageUrl: "https://placehold.co/300x300/FFB7C5/333?text=Sumikko",
    price: 400,
    series: "すみっコぐらし",
    maker: "タカラトミーアーツ",
    tags: ["キャラクター", "ぬいぐるみ", "すみっコぐらし"],
    sourceType: "web",
  },
  {
    id: "2",
    name: "ワンピース フィギュアコレクション",
    nameEn: "One Piece Figure Collection",
    description: "麦わら海賊団のミニフィギュアセット。全8種類。",
    imageUrl: "https://placehold.co/300x300/FFA500/333?text=OnePiece",
    price: 500,
    series: "ワンピース",
    maker: "バンダイ",
    tags: ["アニメ", "フィギュア", "ワンピース"],
    sourceType: "web",
  },
  {
    id: "3",
    name: "ポケモン クリアフィギュア",
    nameEn: "Pokemon Clear Figure",
    description: "透明素材のポケモンフィギュア。ピカチュウ、イーブイなど全10種。",
    imageUrl: "https://placehold.co/300x300/FFE135/333?text=Pokemon",
    price: 300,
    series: "ポケモン",
    maker: "タカラトミーアーツ",
    tags: ["ゲーム", "フィギュア", "ポケモン"],
    sourceType: "web",
  },
  {
    id: "4",
    name: "サンリオキャラクターズ アクリルスタンド",
    nameEn: "Sanrio Characters Acrylic Stand",
    description: "ハローキティ、マイメロディなどのアクリルスタンド全8種。",
    imageUrl: "https://placehold.co/300x300/FF69B4/333?text=Sanrio",
    price: 400,
    series: "サンリオ",
    maker: "バンダイ",
    tags: ["キャラクター", "アクリル", "サンリオ"],
    sourceType: "instagram",
  },
  {
    id: "5",
    name: "鬼滅の刃 煉獄さんフィギュア",
    nameEn: "Demon Slayer Rengoku Figure",
    description: "炎柱・煉獄杏寿郎のリアルミニフィギュア。全4種。",
    imageUrl: "https://placehold.co/300x300/FF4500/333?text=Kimetsu",
    price: 500,
    series: "鬼滅の刃",
    maker: "メガハウス",
    tags: ["アニメ", "フィギュア", "鬼滅の刃"],
    sourceType: "twitter",
  },
  {
    id: "6",
    name: "ちいかわ マスコットキーホルダー",
    nameEn: "Chiikawa Mascot Keychain",
    description: "ちいかわ、ハチワレ、うさぎのキーホルダー全6種類。",
    imageUrl: "https://placehold.co/300x300/98FB98/333?text=Chiikawa",
    price: 300,
    series: "ちいかわ",
    maker: "タカラトミーアーツ",
    tags: ["キャラクター", "キーホルダー", "ちいかわ"],
    sourceType: "tiktok",
  },
];

export const mockSocialPosts: SocialPost[] = [
  {
    id: "t1",
    platform: "twitter",
    text: "すみっコぐらしのガチャ新発売！全6種類でコンプリートしたい🎪 #ガチャガチャ #すみっコぐらし",
    imageUrl: "https://placehold.co/400x300/FFB7C5/333?text=Twitter+Post",
    url: "https://twitter.com",
    author: "gacha_lover",
    likes: 234,
    createdAt: new Date().toISOString(),
  },
  {
    id: "i1",
    platform: "instagram",
    text: "今日のガチャ戦利品🎉 サンリオのアクリルスタンド当たった！ #カプセルトイ #サンリオ #ガチャガチャ",
    imageUrl: "https://placehold.co/400x300/FF69B4/333?text=Instagram+Post",
    url: "https://instagram.com",
    author: "capsule_diary",
    likes: 512,
    createdAt: new Date().toISOString(),
  },
  {
    id: "tk1",
    platform: "tiktok",
    text: "ガチャ100回チャレンジ！ポケモンコンプリートなるか？ #ガチャガチャ #ポケモン #カプセルトイ",
    imageUrl: "https://placehold.co/400x300/FFE135/333?text=TikTok+Post",
    url: "https://tiktok.com",
    author: "gacha_challenge",
    likes: 8920,
    createdAt: new Date().toISOString(),
  },
];

export const mockRanking = [
  { rank: 1, query: "ちいかわ", count: 15420, trend: "up" as const },
  { rank: 2, query: "ポケモン", count: 12300, trend: "up" as const },
  { rank: 3, query: "すみっコぐらし", count: 9800, trend: "stable" as const },
  { rank: 4, query: "サンリオ", count: 8750, trend: "up" as const },
  { rank: 5, query: "ワンピース", count: 7600, trend: "down" as const },
  { rank: 6, query: "鬼滅の刃", count: 6500, trend: "down" as const },
  { rank: 7, query: "呪術廻戦", count: 5400, trend: "up" as const },
  { rank: 8, query: "ハローキティ", count: 4300, trend: "stable" as const },
  { rank: 9, query: "ドラゴンボール", count: 3800, trend: "stable" as const },
  { rank: 10, query: "マリオ", count: 3200, trend: "up" as const },
];

export const mockStores = [
  {
    id: "s1",
    name: "イオンモール幕張新都心",
    address: "千葉県千葉市美浜区豊砂1-1",
    lat: 35.6484,
    lng: 140.0443,
    machines: 15,
  },
  {
    id: "s2",
    name: "アキバガチャポン会館",
    address: "東京都千代田区外神田4-3-3",
    lat: 35.7021,
    lng: 139.7723,
    machines: 500,
  },
  {
    id: "s3",
    name: "ヨドバシカメラ マルチメディアAkiba",
    address: "東京都千代田区神田花岡町1-1",
    lat: 35.6984,
    lng: 139.7730,
    machines: 50,
  },
];
